### ISSUE TITLE
Day and Month SLE/skin missing?

### ISSUE THREAD

**Issue by poblabs** [gjr80/weewx-highcharts#5]
Hey there, I've been using the highcharts extension for a couple of years now, thanks again for the help early on setting it up. 

I'm working on releasing a weewx skin that's a clone of my weather site, and it uses the highcharts extension as an optional dependency. Preparing for that dependancy though I installed the extension fresh on my lab system and saw that the day and month SLE and skin files were gone. Were those removed on purpose or an oversight?

In the version of `highchartsSearchX.py` that I have, they are there and I can't recall if that was original to your code or if I added them long ago?

Anyways - wanted to check in to see if they should be added as they do have value.

**Comment by gjr80** [comment]
Hi Pat,

Sorry, missed this somehow.

Just sat here for 10 minutes trying to work out what has happened, if I go back to the original commit in this repo the day and month SLE/templates are not there. I think what happened is that when I helped you set up your highcharts plots (I remember now, it was Dec 2015/Jan 2016 when I was over your part of the world - I remember emailing/messaging you and all I had was the iPad) it was before I created this repo (initial commit Nov 2016) and I changed the format of my highcharts plots in between. I previously mimicked the default WeeWX plots ie day, week, month and year (and this is what i set you up with) but later on in 2016 I decided to cut down on all the json files being created as well as the supporting SLE and I went to just two plots; a 7 day plot and a calendar year plot. That's the beauty of Highcharts (well Highstocks) you can have a 7 day plot but with a sliding window to show 1 hour, 1 day or 7 days at a time. The 7 day plot is just like the WeeWX day/week plots in as much as it displays actual archive data whereas the calendar year plot displays day min/max/avg. Probably better explained if you look at my plots [here](https://weather.therodericks.id.au/saratoga/wxgraphs.php).

Not sure on the way ahead. Am more than happy for you to do what you want with the code you have. I could probably wrap them up in a legacy release and attach it here under releases. Of course you can use what is currently here but I suspect that is not what you want. What are your thoughts?

Gary

**Comment by poblabs** [comment]
Ah, interesting! So I have some exclusive functions? 😆 Pretty sure I've modified them too since they have my `POB` comments throughout. 

Initially my plan was to have the user setup your extension as part of a manual dependency if they wanted the graphs, but since I seem to have some legacy data I'm not sure of the right way forward either. I could include the extension files that I have with my skin repo and give credit to you for it? 

Or I could do a pull request with the files I have now, and you can include it as a legacy release here as you mentioned. I could then instruct users to download the specific legacy release? The differences between what you have today and what I have are just a few functions for the day and month plots, and some supporting functions. 

I did modify some of the JavaScript files to have a different theme which I was going to include in my release. But those JS files wouldn't work unless they installed the full highcharts extension. 

I'm trying to keep it a simple process for users who want to install the skin, but It's your project and I am open to what you'd like to do.

**Comment by gjr80** [comment]
On giving it some more thought, why don't you package it up and include as an optional extension. I presume you will be making your 'skin' available via Github or the like? If so it would be a fairly easy one-off task to package up the Highcharts code you have and make it available to your skin users if they want. Don't know if you have packaged any WeeWX extensions but it is dead easy. Would probably need some basic extension/manual install instructions and maybe some basic config instructions (changing units always comes up). That way it will stop people being confused by anything they may see in my repo as well as making it fairly clear it's yours.  Makes it much easier if you want to change anything in the future too.

**Comment by poblabs** [comment]
That sounds good. I haven't packaged a skin or an extension yet but you're right, it does look easy. 

Do you suggest I add the highcharts extension I have as part of the skin - or as a separate (forked) repo with instructions on how to download my forked version?

**Comment by gjr80** [comment]
Yep it is easy. Really only two things to worry about. Firstly, getting the installer properly configured, but that is largely just a case of setting up a few descriptive fields and telling it what files to install where. Easiest approach is to look at a working one and you should pick it up. Second is to create the package. I maintain an extensions directory and just add a new directory for a new extension and put the extension tree and files underneath, just as it would be in a WeeWX install. Then the following command to create the package:
```
tar cvfzp /home/gary/weewx_extensions/rtgd-0.3.4.tar.gz -C /home/gary/weewx_extensions rtgd
```
I believe there is also a way to just zip up a GitHub repo to create the package. It's easier but it packages everything in your repo which you may not want to to. I think Matthew does this for some/most of his extensions. Not sure, have never looked into it or used it.

Part of the skin or not, hmmm, guess there are a few ways to go here. Looking at your site it seems the graphs are certainly pretty integral to the main page and who isn't going to want the graphs page as well. Especially when they have the same look and feel as the main page. I would include them. Not knowing how your 'skin' will be structured but you should be able to fairly easily configure things so that it is a very easy 'flick of the switch' in weewx.conf to turn on or off the graphs. I guess it comes down to you distribute with graphs on by default or graphs off by default.

By the way, you are structuring the install such that the user tweaks config options in weewx.conf rather than directly in skin.conf aren't you? The former preserves user settings across upgrades of your extension - makes life much easier for you as a developer.

**Comment by poblabs** [comment]
Good tips on packaging it up. I have a few vanilla test vm's to test with, so I'll give that a go tomorrow. 

For the options, I have everything in the `skin.conf` currently, and I do have the option to turn graphs on/off, mqtt on/off, radar on/off, radar html src (iframe, gif, etc). I even have the extension download forecast data every X seconds (user defined). Using the file's modified time, this avoids a cron so it's easier for the end user. 

Interesting idea on the `skin.conf` vs `weewx.conf`! I have everything in `[Extras]` within `skin.conf` currently. Perhaps I should move it so it persists across upgrades. 

Your right, the graphs are integral, but the option to disable them is present. My initial plan was to ship it disabled and have the user install your extension. Since I have those extra functions for day and month, then perhaps it makes sense to package it all up as one and have them enabled. I'll provide proper credit and links to your repo for those who read that type of thing. 

At this point the to-do list is down to highcharts, some js cleanup and packaging. Everything else is entirely mirrored. So I think it's ready to ship a beta soon. Only thing is I'm not sure how to test other units. I guess I could put weewx into metric mode and see what happens?

**Comment by gjr80** [comment]
> Interesting idea on the `skin.conf` vs `weewx.conf`! I have everything in `[Extras]` within `skin.conf` currently. Perhaps I should move it so it persists across upgrades.

The two things I follow when putting 'stuff' in a config file; make sure you have sane defaults, you want it to work out of the box and secondly do what you can to keep the user out of any config files you distribute because user changes will not survive upgrades of your code. 

By all means put your sane defaults in `[Extras]` but you then get the user to override them from a `[[[Extras]]]` stanza under your skin under `[StdReport]`. Two approaches you can use; repeat your sane defaults in `weewx.conf` and in your config instructions you say 'edit these `weewx.conf` settings as required' or you can omit the `[[[Extras]]]` from `weewx.conf` but then you need explain how to add them in your config instructions. I favour the former, you could argue it is doubling up/repeating but with the sane defaults in `skin.conf` your skin will work just by calling it from `[StdReport]` with no overrides and by putting the `[[[Extras]]]` under `[StdReport]` you are making it a bit easier/more obvious for users. And from my experience we have users with experience/knowledge across the entire spectrum.

> Only thing is I'm not sure how to test other units. I guess I could put weewx into metric mode and see what happens?

Yep testing units is the big one. How safe you will be will depend on how you have handled any data you may have obtained from the db via SLEs etc. If you have observed the `usUnits` values of any records you have obtained through queries etc chances are you will be fine, if you have just used plain numbers without taking notice of `usUnits` then you will likely have an issue with any obs that can use multiple units. I think my initial code observed units so hopefully set you off on the right tracks. Probably worth your while testing a US units db (the default) to ensure it displays US units correctly (expect that one is fine as that is how you will be operating at present) and then changing your skin to display metric, shouldn't be too involved to test, just looking at it will show you pretty quickly whether you have it right or wrong. Probably also worthwhile testing against a metric units db, I know a few folks use metric dbs cause they just like to see their raw data in familiar units. I do and it has tripped me up a few times, but not generally with extensions.

**Comment by poblabs** [comment]
> Two approaches you can use;

Could I use the install.py to load the defaults into weewx.conf and not put anything into skin.conf? A lot of my options have descriptors above them in comment fields so the user knows what they're editing, and if install.py can't handle the descriptors, then I could just put it in my readme.md file on GitHub. 

Things like the about page text, footer text, social share links, page titles, etc. are all editable through a conf file variables and inserted using `$Extra` tags, so I'd want that to be easy to change and not get overridden on upgrades.

**Comment by poblabs** [comment]
Ok, I didn't think it would cause much issue. Will have to play around with it a bit more on some vanilla systems to see how it goes.

**Comment by poblabs** [comment]
After a bit more reading, I understand the concept now. I think I'm good to release a beta and see how it goes. Anyways, thanks for the help and thanks for the permission to package your extension with the skin. Will give you credit once it's released!

**Comment by poblabs** [comment]
@gjr80 Hope you don't mind me reaching you here, again. I didn't want this one to get lost in that long thread in the user forum. 

As I get more familiar with how Cheetah works, I'm realizing that the SLE is run for every `.tmpl` file. Seems like madness but it is what it is. So to optimize I am thinking the highcharts needs to be in it's own skin directory as you've mentioned previously. I was trying to keep it simple but I don't think I can keep them together when some users are having skin generation times longer than their archive. 

With that said, I have a working `install.py` thanks to your weewx-wd as an example. Thanks for that. 

The question I have is users who are upgrading from the "combined" skin (`skins/belchertown`) to the "separated" skins (`skins/belchertown` and `skins/belchertown_highcharts`) are going to run into an issue where the highcharts json.tmpl files are still in the wrong `skins/belchertown` folder. What would be the best way to go about this? Huge bold letters in the release notes to backup their config files, `--uninstall` the extension, then install the new one? 

I was hoping the `install.py` would purge the skins folder of "extra" files, but appears that it does not.

**Comment by poblabs** [comment]
Confirmed that splitting the skins out works. I sent it to the Pi Zero user who was seeing 560 second generation times, and it knocked it down to 145 seconds. Probably as best as it'll get for a Pi Zero. 

So I guess I have my new update for the skin. Just a matter of communicating the uninstall process and the fresh re-install since it's a larger change knowing that install.py won't purge old files. 

Unless you have a workaround?

**Comment by gjr80** [comment]
Sorry I have taken a few hours to reply to this, I wanted to get a clearer picture in my mind of `wee_extension` and the upgrade process.

The `--uninstall` process is destructive in that everything the installer installed is removed/deleted though a copy of the pre-uninstall `weewx.conf` is created (`weewx.conf.yyyy.mmddhhmmss`). So `--uninstall` followed `--install` will solve the issue of files/directories that have been moved, the only problem is if you have an extension that relies on the user to customize settings in a stanza that the installer installed any user changes will be lost (note that `--uninstall` will leave any stanzas that `--install` did not install).

The other approach to an upgrade is to just install the new extension with no `--uninstall`. This approach will preserve any user modification to any stanzas your installer places in `weewx.conf` but I do not believe it will delete any files/directories that have moved. The user would need to manually delete the old files/directories.

In your case the 'moved' files/directories are just a couple of files moved to a new directory, the old directory will remain. If you to take the second option, install new over old:

1. User changes to `weewx.conf` will be preserved
2. A couple of now unused files will remain in a skin directory that the user will need to delete. If the user chooses/forgets/does not delete these files there is no real consequence as you will have updated the `skin.conf` for this skin to no longer use those files.
3. I am not 100% familiar with your skin but I expect the user will need add some customized settings for the new skin under `[StdReport]` in `weewx.conf` (these may or may not be the same as (some of) the user customized settings for your original skin.

If you take the `--uninstall` approach the user will need to copy config settings from the backed up `weewx.conf` to the post-install `weewx.conf`. There will be no files to delete but I expect the user may well have some customised settings to add for the new skin under `[StdReport]` in `weewx.conf`.

I would normally favour the `install new over old approach` mainly for the preservation of user changes to `weewx.conf` but in this case, given your user base is low and the fact that irrespective users will likely have to add/change settings in `weewx.conf`, I would tend to do the `uninstall old then install new`. Further, given there has been a bit of 'file swapping' going on outside of `wee_extension` as you have addressed issues with some users, I would also ask the user to take a copy of `weewx.conf` before backing up; `wee_extension` is great but it can be easily confused if you start doing/changing extension related things without using `wee_extension`.

Whatever you do do, I would certainly get a running system with your old version and some user customized settings then do the upgrade following the steps exactly as you write them and make sure the result is as expected.

Hope this helps.

**Comment by poblabs** [comment]
Great tips and echoes some of my thoughts. I think I'll take the uninstall approach since it's only a handful of users. 

I have 3 virtual machines (apt, setup.py, and different timezone and units) which I've been doing my testing on. I'll revert those back to my old version, and upgrade them a few times to make sure I have it written correctly. I'll then outline the steps in the Release Notes... then wait for the help tickets to come in. 

It may be a bit confusing up front to go through the process of backing up `weewx.conf`, uninstall, the extension, look for any lingering files (this has happened twice to me now although it's low priority since the majority of files are deleted), then reinstall - but I think it'll be worth it to have a clean slate with the new skin setup. I'm hoping this will clear up a lot of the latency some users are experiencing. So far it does seem promising - and I should have taken your advise at the onset. All part of a learning experience. 

I'll do some testing over the next day or so to make sure I've got it nailed down. 

Thanks again for the tips!
